EXCLUDE_IDS = {
    'cafageiakakrlemarisc20a',
    'helmertrs+11',
    'iclp-tc20',
    'lokasebogekobrhorianwesmfo00a',
    'ststfekomawaliatcokubabo19b',
    'baraltt02',
    'agcafapepevi24a',
    'gekaza20a',
    'hacjue04a',
    'hansson99a',
    'prismo93',
    'vogrdabicrorlalagiackljo14a',
    'bibel:c11',
    'poogoe86',
    'schneeberger89a',
    'tornquist06a',
    'cav12',
    'lwda18',
    'lwda22',
    'padl19',
    'vldb06',
    'ruleml22',
    'datalog10',
    'dix92b',
    'leasombe90',
}

WHOLE_NAMES = {
    "The STREAM Group",
}

SPLITED_NAMES = {
    # ('Alan', '', 'Prince', ''),
    # ('Andy', '', 'Cranny', ''),
    ('Ch.', '', 'Goller', ''),
    # ('Chitta', '', 'Baral', ''),
    ('Chr.', '', 'Walther', ''),
    # ('Le-Chi', '', 'Tuan', ''),
    ('Me.', '', 'Bienvenu', ''),
    # ('Michael', '', 'J{\\"u}nger', ''),
    # ('Nam', '', 'Tran', ''),
    # ('Paul', '', 'Smolensky', ''),
    # ('Sven', '', 'Ove Hansson', ''),
    ('V.S.', '', 'Subrahmanian', ''),
    # ('Christopher', '', 'Habel', ''),
    # ('Ehud', '', 'Shapiro', ''),
    # ('Guillermo', '', 'Morales Luna', ''),
    ('H.-J.', '', 'Ohlbach', ''),
    # ('Leo', '', 'G. Kroon', ''),
    ('P.H.', '', 'Schmitt', ''),
    # ('Rolf', '', 'H. M{\\"o}hring', ''),
    ('St.', '', 'H{\\"o}lldobler', ''),
    ('Th.', '', 'Nielsen', ''),
}


JOURNAL_MAPPING = {
    '{ACM} Comput. Surv.': 'acmcs',
    '{ACM} Trans. Comput. Log.': 'tocl',
    '{ACM} Trans. Database Syst.': 'tods',
    '{ACM} Trans. Program. Lang. Syst.': 'toplas',
    '{AI} Commun.': 'aicom',
    '{AI} Mag.': 'aim',
    '{IEEE} Intell. Syst.': 'isa',
    '{IEEE} Trans. Knowl. Data Eng.': 'tkde',
    '{SIAM} J. Comput.': 'sicomp',
    'Acta Informatica': 'acta',
    'Adv. Eng. Informatics': 'aei',
    'Ann. Math. Artif. Intell.': 'amai',
    'Artif. Intell. Eng. Des. Anal. Manuf.': 'aiedam',
    'Artif. Intell.': 'aij',
    'Commun. {ACM}': 'cacm',
    'Comput. Intell.': 'ci',
    'Electron. Trans. Artif. Intell.': 'etai',
    'Inf. Process. Lett.': 'ipl',
    'Int. J. Softw. Tools Technol. Transf.': 'jsttt',
    'J. {ACM}': 'jacm',
    'J. Appl. Non Class. Logics': 'jancl',
    'J. Artif. Intell. Res.': 'jair',
    'J. Autom. Reason.': 'jar',
    'J. Comput. Syst. Sci.': 'jcss',
    'J. Data Semant.': 'jds',
    'J. Intell. Manuf.': 'jim',
    'J. Log. Comput.': 'jlc',
    'J. Log. Program.': 'jlp',
    'J. Satisf. Boolean Model. Comput.': 'jsat',
    'J. Symb. Comput.': 'jsc',
    'J. Symb. Log.': 'jsl',
    'J. Univers. Comput. Sci.': 'jucs',
    'New Gener. Comput.': 'ngc',
    'Theor. Comput. Sci.': 'tcs',
    'Theory Pract. Log. Program.': 'tplp',
}

SKIP_JOURNALS = { 'ai' }

GROUPING_NAMES = {
    'Juan Carlos Nieves' : 'Juan Carlos | Nieves',
    'Tran Cao Son' : 'Tran Son | Cao',
    'Cesar Augusto Tacla' : 'Cesar Augusto | Tacla',
}