[special_names]
"The STREAM Group" = "The STREAM Group"
"Juan Carlos Nieves" = "Juan Carlos | Nieves"
"Tran Cao Son" = "Tran Cao | Son"
"Cesar Augusto Tacla" = "Cesar Augusto | Tacla"
"K. von Luck" = "K. | von Luck"
"M. de Rijke" = "M. | de Rijke"
"W. van der Hoek" = "W. | van der Hoek"
"J. van Leeuwen" = "J. | van Leeuwen"
"S. de Givry" = "S. | de Givry"
"L. de Moura" = "L. | de Moura"
"N. da Costa" = "N. | da Costa"
"H. van Ditmarsch" = "H. | van Ditmarsch"
"W. van der Aalst" = "W. | van der Aalst"
"M. D'Agostino" = "M. | {D}'\\relax Agostino"
"F. van Harmelen" = "F. | van Harmelen"
"O. de Moor" = "O. | de Moor"
"F. Al Machot" = "F. | {A}l Machot"
"G. De Giacomo" = "G. | {D}e Giacomo"
"D. Le Berre" = "D. | {L}e Berre"
"B. Van Nuffelen" = "B. | {V}an Nuffele"
"H. de Nivelle" = "H. | de Nivelle"
"C. Le Pape" = "C. | {L}e Pape"
"N. van Duijkeren" = "N. | van Duijkeren"
"P. van Beek" = "P. | van Beek"
"G. De Micheli" = "G. | {D}e Micheli"
"M. de Glas" = "M. | de Glas"
"V. de Paiva" = "V. | de Paiva"
"P. van Rossum" = "P. | van Rossum"
"M. de Vos" = "M. | de Vos"
"F. De Cesco" = "F. | {D}e Cesco"
"L. Di Gaspero" = "L. | {D}i Gaspero"
"B. De Cat" = "B. | {D}e Cat"
"S. De Pooter" = "S. | {D}e Pooter"
"J. de Kleer" = "J. | de Kleer"
"J. de Bruijn" = "J. | de Bruijn"
"R. Di Cosmo" = "R. | {D}i Cosmo"
"G. Da Col" = "G. | {D}a Col"
"A. Dal Pal{\\`u}" = "A. | {D}al Pal{\\`u}"
"D. van Dalen" = "D. | van Dalen"
"T. De Bie" = "T. | {D}e Bie"
"A. De Rosis" = "A. | {D}e Rosis"
"J. De Kleer" = "J. | {D}e Kleer"
"M. van Emden" = "M. | van Emden"
"M. De Bortoli" = "M. | {D}e Bortoli"
"M. De Cock" = "M. | {D}e Cock"
"A. Van Gelder" = "A. | Van Gelder"
"R. De Masellis" = "R. | {D}e Masellis"
"R. de Guerreiro" = "R. | de Guerreiro"
"M. Van Caneghem" = "M. | {V}an Caneghem"
"C. de Runz" = "C. | de Runz"
"L. De Raedt" = "L. | {D}e Raedt"
"S. Ove Hansson" = "S. | {O}ve Hansson"
"P. Van Hentenryck" = "P. | {V}an Hentenryck"
"R. de Simone" = "R. | de Simone"
"H. van Maaren" = "H. | van Maaren"
"D. de Schreye" = "D. | de Schreye"
"J. van Loon" = "J. | van Loon"
"D. Van Nieuwenborgh" = "D. | {V}an Nieuwenborgh"
"D. Van~Nieuwenborgh" = "D. | {V}an Nieuwenborgh"
"A. Dal Pal{\\`{u}}" = "A. | {D}al Pal{\\`{u}}"
"I. de Guzm{\\'a}n" = "I. | de Guzm{\\'a}n"
"E. Di Rosa" = "E. | {D}i Rosa"
"A. von Kamp" = "A. | von Kamp"
"M. Le Borgne" = "M. | {L}e Borgne"
"B. O'Sullivan" = "B. | {O}'\\relax Sullivan"
"E. De Francesco" = "E. | {D}e Francesco"
"M. de Weerdt" = "M. | de Weerdt"
"B. de Wilde" = "B. | de Wilde"
"A. ter Mors" = "A. | ter Mors"
"A. El Fallah Seghrouchni" = "A. | {E}l Fallah Seghrouchni"
"M. La Rosa" = "M. | {L}a Rosa"
"W. van Hoeve" = "W. | van Hoeve"
"G. Di Natale" = "G. | {D}i Natale"
"J. van den Herik" = "J. | van den Herik"
"A. D'Avila Garcez" = "A. | {D}'\\relax Avila Garcez"
"R. De Benedictis" = "R. | {D}e Benedictis"
"A. von Bernuth" = "A. | von Bernuth"
"B. ten Cate" = "B. | ten Cate"
"J. van de Pol" = "J. | van de Pol"